name: yanyiheyi
description: "言意合一 - 一款优雅的写作应用"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  side_sheet: ^1.0.4+1
  fluttertoast: ^8.2.14
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.1
  confetti: ^0.8.0
  flutter_quill: ^11.5.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.0
  path_provider: ^2.1.2
  crypto: ^3.0.3
  uuid: ^4.3.3
  flutter_quill_extensions: ^11.0.0
  flutter_localizations: 
    sdk: flutter
  chat_bottom_container: ^0.4.0
  talker_flutter: ^5.1.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.svg
    - assets/data/mock_articles.json
    - assets/images/

  fonts:
    - family: LXGWWenKai
      fonts:
        - asset: assets/fonts/LXGWWenKai-Light.ttf
          weight: 300